### ISSUE TITLE
FEATURE: Start-up Page 

### ISSUE THREAD

**Issue by marina8888** [ultrahorizon/UH-VPN-Docs#10]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
When using this app for the first time, I did not realise that to connect to UH VPN, the user needs to open the app first before clicking the icon in the ribbon bar. I found the process for setting up profiles very easy but wasn't sure about the next step after that. 

Perhaps some instructions somewhere in the documentation guide or as a pop-up when the app is first installed could be nice so the user knows where to look. 

**Describe alternatives you've considered**

**Additional context**

**Comment by AnthonyWharton** [comment]
So far the key focus has been functionality, but user onboarding is super important!

Again with the windows release fast approaching, I’ll be free to handle app improvements like these. I’ll be looking at introducing onboarding in the next month or to, but for now your safe bet is deferring to our documentation at docs.uh-vpn.com! Thanks :)

**Comment by marina8888** [comment]
Ok, awesome :) I'm only suggesting things as a user so thank you very much for considering. 

Also, Anthony:
Digital Ocean : "let's do something nice for that VPN company and feature them in our newsletter"
1,000 Droplet users who've all just found the raise issue button: "Imma end this man's career."
XD

Have a lovely day !

**Comment by AnthonyWharton** [comment]
Basic onboarding is included in Windows from v1, and will be included in the new update to macOS (2.0.2) which has just been pushed to the Mac App Store. Expect it to be around in the next few days pending approval.

**Comment by marina8888** [comment]
Fantastic, thank you very much Anthony!! :D))
