### ISSUE TITLE
BUG: on Ubuntu 18.04 software-properties-common and net-tools need to be installed

### ISSUE THREAD

**Issue by marceljd** [ultrahorizon/UH-VPN-Docs#11]
I followed the Ubuntu instructions on a freshly installed VPS and discovered 2 things:

- you need to install software-properties-common to be able to add the UH-VPN repository
- you need to install net-tools to be able to use route in the python script. The server will exit immediately if net-tools is not installed.

Both packages were not installed by default on my VPS, perhaps adding this to the Ubuntu instructions will help others.

**Comment by jwsi** [comment]
@marceljd, this is an excellent spot. I will update the dependencies for the server shortly to include these two pieces of software. I believe we missed this on our internal testing as most cloud providers include these two packages by default in their base images.

We're just about to release version 1.1.0 of the server software to allow the UH VPN API to contact servers dynamically on config changes as opposed to polling every minute. In addition the software will shortly be available on eaon, focal and groovy.

When the update is live and the dependencies are included, I'll close this issue. Thanks again.

**Comment by jwsi** [comment]
`uh-vpn-server` version 1.1.0 now contains the `net-tools` dependency as standard. The documentation has been updated to ensure `software-properties-common` is installed before trying to add a new PPA.
