### ISSUE TITLE
QUESTION: iPhone app connecting only via TCP but not UDP

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#12]
A new Digital Ocean droplet using marketplace and proper DO firewall settings (allowing both TCP 443 and UDP 443 inward connections) does not work on a new server created using UDP/443 but works fine on TCP/443.

1. Go to Digital Ocean / Create new Droplet using DO instructions on UH website. KEEP THIS AS UDP 443.
2. Once the server is authenticated using token, using the web interface set up group, server, user, device as per standard process.
3. on iPhone / install UH VPN app / check email with code / select server.....
4. Click connect (and never connects and takes ages).

Expected behavior: VPN connects and can be checked using leaktests on the web.

Other info:
 - OS: iOS 13.5 running on iPhone X
 - Device: [e.g. iPhone X

**Additional context**
I am not using IPv6 or private VPC options etc. Please note TCP connection works perfect.

**Comment by jwsi** [comment]
This is not a bug on the iPhone app, but instead what looks to be happening is that UDP is being blocked by your ISP. Lots of ISPs do this in an effort to improve quality of service or prevent apps like WhatsApp functioning correctly.

If I were you I'd create two servers, one UDP one and another TCP one and use the TCP one only when UDP does not work :)

**Comment by jwsi** [comment]
For reference -> see [this comment](https://github.com/ultrahorizon/UH-VPN-Docs/issues/7#issuecomment-634979934) in #7 for some ideas on protocol/port combos in countries with censored Internet connections.

**Comment by AnthonyWharton** [comment]
Just to add to James’ point, we make use of UDP 443 servers quite regularly, hence their inclusion on the guide. It definitely does work!

We’ll be discussing internally about improvements for those on censored connections as this isn’t the only issue to bring this up.

Thanks for trying UH VPN!
