### ISSUE TITLE
FEATURE: Documentation should cover all features

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#13]
I became a new premium customer today. I find that the basic documentation is good. But the documentation does not cover some of the free as well as premium features advertised. 
- Dual Stack
- Custom Cryptography
- Custom branding - For features other than just the logo.
- Split routing

Grateful if you could enhance the documentation to cover the above features.

**Comment by jwsi** [comment]
@sunny75016 good idea. We'll work on producing some advanced tutorials to cover these topics ASAP. I'll go ahead and reference this issue again when these tutorials are complete.
