### ISSUE TITLE
QUESTION: Will MTU matching help boost the speed further?

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#15]
My UH-VPN installation on DO Droplet is already giving fantastic speed. In the /var/log/uh-vpn-server/[filename redacted for privacy].log file I noticed the warning below. It seems to be timed with re-booting of the droplet but I could not wrong about the timing.

WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1552', remote='link-mtu 1524'

I do not know whether tackling this warning could boost the speed further. Over to you for your kind consideration.

**Comment by AnthonyWharton** [comment]
This warning can be safely ignored. Different networks will have different MTU's, so even if you fix it for the network you are connecting to your server on now, it may change if you connect from somewhere else!

If the MTU difference is very great then there could be a bit of a performance pentalty, but a difference of two bytes shouldn't be the end of the world!
