### ISSUE TITLE
FEATURE: Add stricter security to VPN Profile Emails

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#17]
The automatic emails sent to users (containing code and links to apps) are reaching spam folders.

I have identified that the domain uh-vpn.com has not yet set its SPF, DKIM and DMARC records. These are the minimum essential security practices and improve the chances of email delivery. In addition, DNSSEC, STARTTLS and DANE are recommended. This should be very easy to This is very easy to do; but happy to help if needed.

**Comment by jwsi** [comment]
@sunny75016 all emails come from `smtp.uh-vpn.com`, this has the required SPF & DKIM records. If you follow the message headers in the source you should see that it verifies correctly.

**Comment by AnthonyWharton** [comment]
Thanks for your rather thorough reviews! 😛 

For reference from my machine `dig smtp.uh-vpn.com TXT` returns:

```
; <<>> DiG 9.11.5-P4-5.1+deb10u1-Debian <<>> smtp.uh-vpn.com TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35989
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;smtp.uh-vpn.com.               IN      TXT

;; ANSWER SECTION:
smtp.uh-vpn.com.        300     IN      TXT     "v=spf1 include:amazonses.com ~all"

;; Query time: 27 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu May 28 17:32:38 BST 2020
;; MSG SIZE  rcvd: 105
```

I'll also just add that adding DMARC in the works as we speak! 

As an aside, realistically we have checked emails on a variety of popular public email providers, along with our Enterprise clients, including set ups with email filtering with "next generation firewalls" (bit buzzwordy but without breaching NDA's, in this general category) and we have not had issues in loosing emails to spam.

There's always room for improvement but we are juggling a lot of balls in bringing this release public so we appreciate your patience! If there are stricter requirements that you require please detail them further and we'll see if we can facilitate them into our service.

**Comment by sunny75016** [comment]
Thanks for the prompt feedback. I investigated further. The recipient mailserver is protonmail.com. It saw the from as "no-reply@uh-vpn.com" and also sender as [code reacted for privacy]@smtp.uh-vpn.com.  I see that you added spf on smtp already. Absolutely no rush. You can classify this as feature instead of bug if you wish. Always happy to help.

**Comment by jwsi** [comment]
@sunny75016 thanks for providing more information. We will create a protonmail account internally and do some further testing to establish why this is happening for this particular vendor.

**Comment by jwsi** [comment]
DMARC policy has now been applied. In addition, UH VPN emails were not going to SPAM upon testing with protonmail after the DMARC inclusion.

@sunny75016 if this issue is still present after our changes, please feel free to re-open this issue and send headers for the message and we'll have a look at what's going on.
