### ISSUE TITLE
FEATURE: 2FA for web interface login

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#18]
We have enabled login-2FA for all of our other service providers that provide such feature. Whilst we are still experimenting with your vpns (and the initial result is superb), it will be useful 2FA in the wishlist of features.

**Comment by jwsi** [comment]
@sunny75016 this is definitely in the pipeline. We are currently in the process of migrating authentication to a different provider (AWS Cognito). Once this is complete, the 2FA option will become available and the option will be presented in the profile page on the UH VPN website.

**Comment by jwsi** [comment]
We have now created our own authentication system and have successfully transitioned away from Auth0. MFA is now being worked on and should be completed fairly swiftly 👍

**Comment by jwsi** [comment]
Hi all, this has now been implemented and MFA can be enabled from your profile page within UH VPN.

The MFA system uses the [TOTP mechanism](https://tools.ietf.org/html/rfc6238) which works with apps like Google Authenticator, Bitwarden and many more. You can simply scan the presented QR code or manually enter the TOTP secret to start getting 6 digit codes. Once this is done, simply enter a correct code in the modal prompt to enable MFA for your account.

If any issues occur with this please comment here and re-open this issue.

James.
