### ISSUE TITLE
QUESTION: I don't understand the billing

### ISSUE THREAD

**Issue by Takumi86ES** [ultrahorizon/UH-VPN-Docs#19]
I pay £ 1 per device to use. Will I be charged £ 1 for each device I add?

By the way; very nice the web and everything well explained. My congratulations. I am waiting for the Windows application.

**Comment by AnthonyWharton** [comment]
Thanks for the interest!

Yes that’s right, you are billed £1 (+VAT if in a European country) for every device that you add. If you add a device and then remove it, you will still be charged for that device for that month, as you are charged for the maximum number of devices you used in that month.

**Example:**

**Month 1:** Have 4 devices. Charged £4 (+VAT).

**Month 2:** Create 2 more devices, then delete 3 devices. End the month with 3 devices but had a maximum of 6 devices during that month. Charged £6 (+VAT).

**Month 3:** No changes, remain on 3 devices. Charged £3 (+VAT).

—-

Thanks for the support. The Windows app is just undergoing the last few tests today and then we should be pushing it public - the release is imminent!

**Comment by jwsi** [comment]
@Takumi86ES The windows application has now been released.
