### ISSUE TITLE
FEATURE: WHMCS module

### ISSUE THREAD

**Issue by Takumi86ES** [ultrahorizon/UH-VPN-Docs#21]
It would be nice to be able to create a WHMCS module to automate user / device creation. I guess this I know can be done with an API.

It would be helpful for people who will use UH-VPN to re-sell VPN services.

**Comment by AnthonyWharton** [comment]
On the surface this seems like a fairly large feature request, or perhaps that's because I'm too familiar with WHMCS!

We've been internally discussing different potential integrations in our roadmap for the future for person and device management.

We will add this into consideration, thanks.

**Comment by AnthonyWharton** [comment]
Edit due to fat fingered typos on my phone, I’m not at all familiar with WHMCS! Edited my comment above!

**Comment by jwsi** [comment]
@Takumi86ES please could you describe a little about how you think this integration would work and give us a little more detail into how/what WHMCS is?

Once this is done, we can perhaps leave this issue open and allow users to upvote the request. If this gets enough votes we can perhaps look at considering it.

**Comment by jwsi** [comment]
@Takumi86ES we'll reopen this issue when you provide a response to the above.

**Comment by allymitton** [comment]
@jwsi @AnthonyWharton 

In my opinion, WHMCS is the best automation and billing platform aimed at hosting providers using software such as cPanel, Plesk, Direct Admin. Other integrations for deploying VPS or VMs, and many 3rd party plugins for application hosting such as game servers, are available on their marketplace.

Many VPN providers have added their plugins also, please see https://marketplace.whmcs.com/product/5051-vpn-reseller-module

We've been trying your platform and love it so far. As our business is structured on automation, provisioning accounts automatically after payment is a must. This means we would have to invest time in our developers to integrate our billing systems to your platform when there are other VPN providers who have off-the-shelf solutions with a few clicks.

+1 from me for WHMCS integration...
Keep up with good work,
Ally

**Comment by jwsi** [comment]
Hi @allymitton,

Thanks for providing a little more insight into WHMCS. We're actually developing a public API for UH VPN as we speak and this is due to be released fairly soon. This API specification has all the endpoints required to create new persons, devices etc. I believe that will be a great generic solution for a lot of people wishing to resell UH VPN through such platforms. Therefore, once this is released it should be fairly simple for companies such as yourself to hook the UH VPN API into WHCMS or a platform of your choice.
