### ISSUE TITLE
Is the Openvpn version upgrade automatic?

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#23]
I have install UH VPN on an Ubuntu 20.04 vps from your ppa using the standard installation (sudo apt-get install uh-vpn-server).

openvpn --version shows 2.4.7  (which looks like the default version in the Ubuntu repository). The current openvpn stable version, as we know, is 2.4.9.

Will I be correct in assuming that the openvpn upgrade will take place automatically via the normal apt update / upgrade procedure?  Do you recommend any additional settings / improvement, other than "apt install unattended-upgrades"? Thanks.

**Comment by jwsi** [comment]
Hey @sunny75016 here's the answer to the questions above:

> Will I be correct in assuming that the openvpn upgrade will take place automatically via the normal apt update / upgrade procedure?

Yes this is correct, simply issue the commands:

`sudo apt-get update`
`sudo apt-get upgrade`

When Ubuntu have updated their PPAs to include the latest stable version of openvpn, it will be installed via this process. Please note when openvpn updates, it may be necessary to restart the `uh-vpn-server` by issuing the command:

`sudo service uh-vpn-server restart`

> Do you recommend any additional settings / improvement, other than "apt install unattended-upgrades"?

I think this is a great place to start, using the unattended-upgrades package to look for security updates is a good idea. Furthermore, if you wanted to you can add the Ultra Horizon PPA to the unattended-upgrades config file, but I think it's best to only install security updates via these means and rely on manual upgrading for VPN software such as OpenVPN or UH VPN Server.
