### ISSUE TITLE
QUESTION: How to use ipv6?

### ISSUE THREAD

**Issue by Takumi86ES** [ultrahorizon/UH-VPN-Docs#25]
I don't have much experience with VPNs. I would like to know how to activate the option to navigate with ipv6.

**Comment by jwsi** [comment]
Hi @Takumi86ES, to use IPv6 with UH VPN you must have a publicly assigned IPv6 subnet issued to you from either your ISP or an Internet registry such as RIPE, ARIN and so on.

Once you have a subnet (E.g. a /56 routed to you from your ISP) you must allocate a /64 for use within UH VPN. To do this simply paste the IPv6 subnet into the "IPv6 Tunnel Network" field on the edit server page within UH VPN. Future connecting clients will then be served both an IPv4 and IPv6 address.

One thing to note is that it's imperative that you route the /64 to your VPN server to avoid NDP issues. I.e. you should have this route in place on your upstream router:

`static route <IPv6_TUNNEL_NET> next-hop <VPN_SERVER_IPv6_ADDRESS>`
