### ISSUE TITLE
FEATURE: Enable/Disable logging on server software

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#26]
UH has its own log policy at https://docs.uh-vpn.com/en/latest/privacy.html which is really good. However, UH VPN installations do maintain upto 12 MB of logs as per
https://docs.uh-vpn.com/en/latest/servers/logging.html

Whilst such logging may be useful for troubleshooting the initial installation - it may not be needed by some customers especially in the production environment or those customers that allow privacy oriented vpns.

Suggested solution:
Include a conf file in /etc/uh-vpn-server  (suggestion: uh-vpn-server.conf)
Allow a flag in that file (suggestion: "ZeroLogs=[true/false]") 
If the customer chooses "true" value of that flag, the uh-vpn-server to stop further logging and also truncate the relevant log files (suggestion: truncate -s 0 /var/log/uh-vpn-server/*.log)

Grateful if you could consider this as a feature.

**Comment by AnthonyWharton** [comment]
Hi @sunny75016, thanks for the feature request.

No logs pertaining to the data transferred by the clients is kept, so from memory the one could really gain potentially is the timestamps of the client connection/timeout.  In addition, maintainly logs from the UH VPN Server Daemon is important for troubleshooting and support if we have clients that have issues whilst deployed, so we may have to reduce support guarentees (not that any formal ones are in place) if users disable logging.

We didn't initially implement this as a feature as we deemed these logs to not be privacy inhibiting but instead useful from an engineering perspective, however now you raise this we're discussing this issue internally and will come up with a more concrete solution/response shortly.

**Comment by jwsi** [comment]
So from my perspective, implementing this as an option on the website isn't necessarily an issue. However, one problem that will arise from this is the issue of the `daemon.log`. One could forsee a situation where logging is enabled on one server, but then disabled on another and then subsequnetly this would cause issues when the daemon has to decide which config to respect.

So it would be possible to remove logging for individual servers and keeping the daemon log which doesn't actually hold any sensitive data anyway. Alternatively, the best bet for now is to add a few `truncate -s 0` commands into the cron to wipe the logs periodically.

I think it's best to do an "ask the audience" style apprach on this where if we get a signifcant amount of thumbs up on the issue we'll implement it!

**Comment by jwsi** [comment]
Please thumbs up this comment if you'd like to see this feature!

**Comment by jwsi** [comment]
Hi everyone, I'm satisfied that enough people want to see this feature. Therefore, I will begin implementing this soon. The new system I propose will add a custom switch per server called "Enable Logging". When disabled, the log for the particular server in question will be removed. However, the daemon log will remain at all times.
