### ISSUE TITLE
FEATURE: Document enhancement for Premium Feature - Custom Cryptography

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#28]
In response to my previous ticket, you have already created a page at https://docs.uh-vpn.com/en/latest/website/servers/custom-crypto.html . Thank you.

It will be nice if you can enhance this page by including a practical example of using OpenSSL and Letsencrypt to generate the key, csr, cert and installing in the Premium Option.

Thanks for considering.

**Comment by jwsi** [comment]
Hi @sunny75016,

The main reason for not doing this is becuase this feature is only meant to be utilised by large corporations who already have a PKI infrastructure in place that they need to use for complaince reasons. UH VPN generates unique keys and certificates for every server and so you're not at risk by not using this feature. **If you don't have an existing PKI in place then don't use it**.

Secondly, using custom crypto options **can be dangerous** if you don't generate the certificates, keys and randomness in an appropriate way. One of UH VPN's key goals is to remove this complexity to make it easier and safer for users to run a VPN protocol.

However, if you'd still like to try it then your best bet is following a guide like [this] (https://openvpn.net/community-resources/setting-up-your-own-certificate-authority-ca/). However, you will not need to generate DH params or client certificates, but you will need to create an OpenVPN static key (just a load of randomness formatted with a header and trailer). You can probably accomplish the static key generation by using one of their tools or by coding up a simple program to do it for you.

**Comment by jwsi** [comment]
I should also add that you can view the certificates issued to servers by either:

a) Editing an existing server, enabling custom crypto option and viewing the data in the input fields.
b) SSH into a server and viewing the files within `/etc/uh-vpn-server/token` where `token` is replaced with your secret server token.
