### ISSUE TITLE
QUESTION: Custom Branded Apps?

### ISSUE THREAD

**Issue by mjshein** [ultrahorizon/UH-VPN-Docs#29]
**Please describe the question you wish to ask**
A clear and concise description of the question. Ex. How do I create a group? [...]

On the pricing page, it says the premium plan has custom branded apps.
How do I get these?

**Comment by jwsi** [comment]
Hi @mjshein,

Custom branding is available on iOS and Android. To enable this simply edit the group you have created, press customise logo and then upload your logo and choose appropriate colours.

**Comment by mjshein** [comment]
Ah, thank you. Have a great night!
