### ISSUE TITLE
FEATURE:  API to create new users and devices

### ISSUE THREAD

**Issue by mynameismax** [ultrahorizon/UH-VPN-Docs#30]
**Is your feature request related to a problem? Please describe.**
It would be great if I could use an API to create new people and devices for them, to help automate the process and make it faster.

**Describe the solution you'd like**
An API that requires verification by a key. The API would only be available to paid users and would allow you to create people and devices.

**Additional context**
Please add this, as it would be extremely helpful! Thanks

**Comment by jwsi** [comment]
Hi @mjshein,

This sounds like a nice idea and something that will likely benefit quite a few of our more advanced users. The website is API driven anyway so the basic framework for doing this is actually already available. However, we are in the process of moving our authentication systems internally and so this feature request will be dependent on #18.

Once #18 is complete, we'll start to flesh out this in more detail internally and keep you updated here.

**Comment by jwsi** [comment]
#18 is now closed, therefore work will start on this in due course.

**Comment by fazil501001** [comment]
Hi friends. tell me why i can't create a group what is the problem on the site there is no group creation

**Comment by fazil501001** [comment]
How much to pay so I can create a group. and where to send money. preferably by paypal

**Comment by jwsi** [comment]
This is now supported on the enterprise platform.
