### ISSUE TITLE
QUESTION: Ports for Firewall to Access UH VPN Server

### ISSUE THREAD

**Issue by terra3110** [ultrahorizon/UH-VPN-Docs#31]
Hi,

I setup UH VPN on my Ubuntu Server and everything works fine until I activate my Firewall. Then the VPN cannot connect anymore. I was not able to find a list of required TCP, IP and UDP ingoing and outgoing Ports to ensure, that it's working. Can you help?

Cheers

Frank

**Comment by jwsi** [comment]
Hi @terra3110,

UH VPN makes use of two ports:

1. The port used for the UH VPN server you're running on your Ubuntu machine. This can be found by looking at your server configuration on the UH VPN [website](https://uh-vpn.com).
2. `TCP 2802` for configuration updates.

The Ubuntu instance of yours will also require outbound Internet access to communicate with the UH VPN API.

If you followed the [Ubuntu setup guide](https://docs.uh-vpn.com/en/latest/setup-guides/ubuntu.html) it should guide you through setting up UH VPN.

Please let me know if enabling firewall access to the two ports defined in the list above solves your issue.

**Comment by terra3110** [comment]
Many thanks. I did not saw the Ubuntu Guide and I opened up the usual Ports for a VPN. Now its working.
