### ISSUE TITLE
QUESTION: Securing DNS queries going out of the VPN exit node?

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#33]
At the moment, the DNS queries get sent to third party DNS servers (e.g. Cloudflare 1.1.1.1 or Google 8.8.8.8) depending on the DNS entries on the UH VPN servers.

Question: Is it possible to secure DNS look ups further, for example by running a DNS server on the same VPS / droplet?  If yes, what changes to the UH VPN server configuration would be required?

**Comment by jwsi** [comment]
Hi @sunny75016,

Yes that's certainly possible. You'll need to install a recursive DNS server on your VPS like `dnsmasq`. Once that's done, you can configure `dnsmasq` to listen on `UDP 53`on a specified IP, then use that IP in the server settings on the UH VPN website. Connecting clients will then use that DNS server as the resolver.
