### ISSUE TITLE
QUESTION: Password reset function does not work (no e-mail received)

### ISSUE THREAD

**Issue by Arnoo-1** [ultrahorizon/UH-VPN-Docs#39]
Hello,

I cannot log into my UH-VPN account anymore and would like to reset my password. I tried the reset button repeatedly, but I do not receive a reset e-mail. Please can you help me getting access to my account again? 

Thank you.

KR, Arno

**Comment by AnthonyWharton** [comment]
Hi there, 

Please could you email `engineering[at]ultra-horizon.com` from the address your account is registered with and I'll look into this/get you a password reset email ASAP.

Thanks,
Anthony

**Comment by Arnoo-1** [comment]
Hi there,

According to the ticket, hereby I request to reset my password (arno@cybercloud.cc <mailto:arno@cybercloud.cc>).

Thank you!

Kind Regards, Arno

**Comment by AnthonyWharton** [comment]
Give me just a moment, thanks!

**Comment by AnthonyWharton** [comment]
You should have a password reset email with you now. Please could you reset your password through the link it provides and let me know how you get on.

Kind regards,
Anthony

**Comment by Arnoo-1** [comment]
Unfortunately, I did not receive it (also not in the spam folder)…

KR, Arno

**Comment by AnthonyWharton** [comment]
Ok, the email definitely should have sent. I have sent another one now. If that one still does not reach me, please could you email `engineering[at]ultra-horizon` directly from the email address in question instead of through GitHub please.

Thanks,
Anthony

**Comment by AnthonyWharton** [comment]
Sorry, typo with the email address, it should have been `engineering[at]ultra-horizon.com`.

Thanks,
Anthony

**Comment by jwsi** [comment]
The underlying bug that caused this behaviour has now been fixed. We didn't account for users forgetting their passwords prior to converting to our new authentication system. This corner case has now been implemented for other users so that they don't have this issue.
