### ISSUE TITLE
BUG: Incorrect link to server documentation on AWS setup guide

### ISSUE THREAD

**Issue by grant-m-s** [ultrahorizon/UH-VPN-Docs#40]
**Describe the bug**
On your AWS setup guide, the follow note: `A full description of all parameters can be found on the server creation docs page.` has the following link to the server creation page: https://docs.uh-vpn.com/en/latest/setup-guides/website/servers/creating.html

This link is not valid and so you get redirected to `This page does not exist`.

**To Reproduce**
1. Go to https://docs.uh-vpn.com/en/latest/setup-guides/aws.html
2. Scroll down to `A full description of all parameters can be found on the server creation docs page.`
3. Click [server creation docs page](https://docs.uh-vpn.com/en/latest/setup-guides/website/servers/creating.html)
4. See `This page does not exist`.

**Expected behavior**
The correct link to the documentation is https://docs.uh-vpn.com/en/latest/website/servers/creating.html

**Comment by jwsi** [comment]
Good spot @grant-m-s!

Would you like to make a PR seeing as you have found the solution? There's the prestigious title of UH VPN Docs contributor up for grabs if you do! 😛
