### ISSUE TITLE
FEATURE: Security features of UH-VPN

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#45]
The product features with a price plan comparison of the VPN is already on the website. However, the security features are not specified anywhere. It will be nice to see one page dedicated to security features. Thanks for adding to the wish-list.

**Comment by jwsi** [comment]
Hi @sunny75016,

Cool idea! I think it would benefit all for us to itemise all of the cryptographic algorithms and protocols used within UH VPN  so that users know exactly what's going on behind the scenes.

**Comment by jwsi** [comment]
There is now a dedicated security section within the docs hub at: [https://docs.uh-vpn.com/en/latest/security.html](https://docs.uh-vpn.com/en/latest/security.html)
