### ISSUE TITLE
FEATURE: Unbiased testing of UH VPN connections privacy

### ISSUE THREAD

**Issue by sunny75016** [ultrahorizon/UH-VPN-Docs#51]
Whenever we search for IP leaktest or DNS leaktest, the search engines come up with online tests offered by vested interests i.e. commercial vpn providers. Invariably the connections via UH VPN servers are shown as vulnerable. Lol. 

It will be nice if UH could indicate which unbiased and independent tests should be used (and how) to ensure privacy of our connections. Nothing urgent, but it will be nice feature to add in the Christmas wishlist.

**Comment by AnthonyWharton** [comment]
Could you provide some examples of tests that you are running?  Do you mean when other VPN services have banners on their website saying that your connection is insecure?  Or are there some specific tests you are referring to?

**Comment by jwsi** [comment]
Generally the way these websites work (especially those offered by commercial VPN providers) is that they compare your IP address to the list of their public VPN server IPs, if a match isn't found they mark it as vulnerable.

**Comment by AnthonyWharton** [comment]
I might add that we would not do this as it would be implicitly providing a means to test for server IP addresses that use UH VPN - something that we don't want to publicise as that is a huge breach of your privacy as UH VPN servers are self-hosted!

**Comment by jwsi** [comment]
As for vulnerability testing, all of these sites are basically useless. The best basic checklist to follow is:

- Use public key SSH authentication (disable password authentication).
- Check open ports on your machine - `sudo netstat -tulpn` - if you spot anything that's not meant to be there, close it.
- Use a firewall like `iptables` or `ufw` to whitelist incoming network connections.
- Ensure regular updates for security purposes - `apt update && apt upgrade`
