### ISSUE TITLE
QUESTION: Trying to use UH-VPN for Netflix et al. Not getting much luck

### ISSUE THREAD

**Issue by edmundsca** [ultrahorizon/UH-VPN-Docs#58]
Hi, Great app. Not your problem I know, but I'm trying to find a DC that isn't blocked by streaming services in the US. Thanks.

**Comment by jwsi** [comment]
Hi @edmundsca,

So most large scale providers such as AWS, Azure and so on will be blocked. Almost all streaming services query your IP address and lookup the ASN (owner of the IP address) and if it matches against a known cloud provider then they will put blocks in place to prevent streaming.

The best way of overcoming this is to use a residential connection. I.e. host a Ubuntu server with UH VPN installed in a home environment and make use of the residential IP allocated by your ISP. Then you shouldn't have an issue with streaming services.

I hope this helps and I'm glad you're enjoying the service.

James.
