### ISSUE TITLE
BUG: THE PRIVATE UH-VPN IS BLOCKING THE CONNECTION TO THE PROXY

### ISSUE THREAD

**Issue by 112Ed** [ultrahorizon/UH-VPN-Docs#59]
**Describe the bug**
The private vpn that I created via uh-vpn is somehow blocking the connection to the proxy via proxifier.

**To Reproduce**
1. start the vpn and start a random app that you put in proxifier in the proxification rules
2. configure the app in the proxification rules, connect it to the proxy
3. when you start it and the vpn is connected, it doesnt connect to the proxy server, but if you turn off the vpn its connecting

**Expected behavior**
Even though the vpn is connected, I should be able to connect the proxy server to the app I want to use.

**Screenshots**
![image](https://user-images.githubusercontent.com/74912065/99965346-699dd980-2d9d-11eb-936f-217b154bfbef.png)
![image](https://user-images.githubusercontent.com/74912065/99965452-8f2ae300-2d9d-11eb-9929-3a164954c730.png)

**Web Console (please complete the following information):**

**Application (please complete the following information):**
 - Device: [e.g. iPhone6] PC
 - OS: [e.g. iOS8.1] WIN 10, UPDATED

**Additional context**

**Comment by AnthonyWharton** [comment]
Hi @112Ed,

Unfortunately we do not support issues that are not related to UH VPN, so we can't help with issues with Proxifier.  However I can say that UH VPN will route all IP traffic over the VPN without modifying it, so it should not be affecting any of your applications.

Things to consider:
 - Whether or not the server you have set up has access to the proxy servers you are trying to connect to?
 - Whether or not you are routing all IPv4/6 traffic in the server settings, or a specific subnet that might not contain the proxy server?
 - Are your VPN server's DNS settings able to see the domains that you are trying to resolve?

Let us know if we can help any more, but for now I'm going to close this issue.
Anthony
