### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by Vijaichand-Francisco-Aguirre** [ultrahorizon/UH-VPN-Docs#63]
**Please describe the question you wish to ask**
A clear and concise description of the question. Ex. How do I create a group? [...]

When my stuff goes in mitigation it turns off ICMP and then people that try to connect to it, it doesn't work
but its not closing the port that it needs what do i do?

**Comment by jwsi** [comment]
Hi @Vijaichand-Francisco-Aguirre ,

I'm really not sure what you're asking. Please re-read what you've written and try to explain in more detail please.

James.
