### ISSUE TITLE
QUESTION: Existing premium customers

### ISSUE THREAD

**Issue by beatquantum** [ultrahorizon/UH-VPN-Docs#69]
Hi James,
In my account, I see no option to change the account plan. I am an existing (premium) customer with several invoices paid using a valid non-fraudulent card via your system. I understand your intention to get rid of fake customers; what are you doing to retain genuine non-enterprise customers?

**Comment by jwsi** [comment]
Hi @beatquantum,

Don't worry we'll be transitioning you onto the enterprise plan at no additional cost. You won't have to make any changes and your group will automatically convert over to the enterprise plan at the same price point.

James.
