### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by fazil501001** [ultrahorizon/UH-VPN-Docs#71]
**Please describe the question you wish to ask**
A clear and concise description of the question. Ex. How do I create a group? [...]

UH VPN REVIEW

**Comment by AnthonyWharton** [comment]
Please can you provide some more information on what you need help with?

**Comment by fazil501001** [comment]
You do not have a button on your site to create a group why.

**Comment by fazil501001** [comment]
Name LicenseRegistration Timeout. This is what the site gives out. I created a vps server and I can’t create a vpn because there is no way to create a group

**Comment by fazil501001** [comment]
How to solve the problem

**Comment by fazil501001** [comment]
How much to pay so I can create a group. and where to send money. preferably by paypal

**Comment by fazil501001** [comment]
When i get the answer guys

**Comment by jwsi** [comment]
Hi @fazil501001,

UH VPN no longer permits the creation of groups on the website. Instead it is now an enterprise-only service. If you'd like to purchase UH VPN please contact engineering@ultra-horizon.com. They will be able to provide a quote and get you set up with the service in no time :)
