### ISSUE TITLE
QUESTION: How i can restore MFA?

### ISSUE THREAD

**Issue by dagolub** [ultrahorizon/UH-VPN-Docs#72]
**Please describe the question you wish to ask**
A clear and concise description of the question. Ex. How do I create a group? [...]

**Comment by AnthonyWharton** [comment]
Hi there,

Please can you elaborate? Are you locked out of your account? If so please email engineering@ultra-horizon.com from the email address owned by the account and we will ask some security questions to help you restore access.

Thanks,
Anthony
