### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by Vijaichand-Francisco-Aguirre** [ultrahorizon/UH-VPN-Docs#73]
I installed Uh VPN And There are no ports closed by default the provider leaves all ports open
Anyways I installed it, The Daemon logs says it got the config for it
But when i try to connect to it using the client
It will just not connect
And it will say reconnecting after a few seconds as well
This was the error
 Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

**Comment by Vijaichand-Francisco-Aguirre** [comment]
This was the error i got  Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

**Comment by Vijaichand-Francisco-Aguirre** [comment]
A Completely new issue now :/
[Check the screenshot](http://image.surf.is-a-cool-kid.xyz/​‌​‌‌‌‌‌‌‌​​‌​‌​‌‌‌​‌‌‌‌‌‌​‌​​​​​​​​‌​‌​​‌​‌‌​​‌‌‌​​​‌‌‌​​‌​​​‌‌)

**Comment by AnthonyWharton** [comment]
Apologies for the very delayed response. Please could you try again from scratch and let me know if you still have the same issue.

If so, please zip up and send over the logs located at `%PROGRAMDATA%\Ultra Horizon\` and `%LOCALAPPDATA%\Ultra Horizon` to engineering@ultra-horizon.com and reference this issue.

Kind regards,
Anthony

**Comment by AnthonyWharton** [comment]
As this issue hasn't had any updates for a long time I'm going to close it. Feel free to reopen if you wish to add more/have any updates.
