### ISSUE TITLE
QUESTION: i can't create an account

### ISSUE THREAD

**Issue by qnyblog** [ultrahorizon/UH-VPN-Docs#77]
https://uh-vpn.com/auth/signup
The requested URL was not found on the server

**Comment by AnthonyWharton** [comment]
Hi there,

Unfortunately public UH VPN sign ups have now been disabled. Please read #68 for more information. Some older subscribers have retained a basic level of access for backwards compatibility, however they too are unable to create new groups.

If you wish to enquire about an enterprise subscription of UH VPN or get a quote, please contact engineering@ultra-horizon.com with your requirements.

Kind regards,
Anthony
