### ISSUE TITLE
Signup not found

### ISSUE THREAD

**Issue by double-square** [ultrahorizon/UH-VPN-Docs#78]
![2021-07-11_22-06](https://user-images.githubusercontent.com/56848395/125207309-48d6b580-e294-11eb-972d-fac8611a2677.png)

**Comment by AnthonyWharton** [comment]
Hi there,

Unfortunately public UH VPN sign ups have now been disabled. Please read #68 for more information. Some older subscribers have retained a basic level of access for backwards compatibility, however they too are unable to create new groups.

If you wish to enquire about an enterprise subscription of UH VPN or get a quote, please contact engineering@ultra-horizon.com with your requirements.

Kind regards,
Anthony
