### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by Jarrod181111** [ultrahorizon/UH-VPN-Docs#85]
There is no link to make a account on the website. I tried on digitalOcean with the link and says Error 404 not found

**Comment by hroland** [comment]
+1

**Comment by AnthonyWharton** [comment]
HI, [I've just answered the same question over here](https://github.com/ultrahorizon/UH-VPN-Docs/issues/84#issuecomment-976889820). I appreciate you taking the time to make an issue, but please look for duplicates as there have been quite a lot! (#84, #81, #78, #77, #75 ... to name some)
