### ISSUE TITLE
BUG: exe not working

### ISSUE THREAD

**Issue by cpeker-extenship** [ultrahorizon/UH-VPN-Docs#86]
**Describe Get-FileHash .\uh-vpn-installer_1.0.4.msithe bug**
Hello, exe is not opening and i really have no idea.

**To Reproduce**
1. Go to Start menu
2. Click on UH VPN
3. No sense

**Screenshots**
![image](https://user-images.githubusercontent.com/64849480/141348508-9a5f71da-2a2d-4b04-8a8b-58afec4424d7.png)

**Web Console (please complete the following information):**
 - OS: Windows 10

**Comment by cpeker-extenship** [comment]
any answer?

**Comment by cpeker-extenship** [comment]
cant use it almost 15 days?

**Comment by cpeker-extenship** [comment]
at least please let me know how i can connect without using your windows app?

**Comment by cpeker-extenship** [comment]
solved via moving openvpn

**Comment by AnthonyWharton** [comment]
Apologies for the delay in response. That's a very strange issue.

Could you detail a little bit more as to what you did to solve the issue?

Thanks,
Anthony
