### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by whoisspy1** [ultrahorizon/UH-VPN-Docs#88]
Hello please fix that problem I'll send you the video 
iPhone 12 Pro Max ios 15.2https://user-images.githubusercontent.com/78816297/146651536-db2d7704-5269-4c87-bec0-c796bd251bbb.MOV

**Comment by inet45** [comment]
> Hello please fix that problem I'll send you the video iPhone 12 Pro Max ios 15.2https://user-images.githubusercontent.com/78816297/146651536-db2d7704-5269-4c87-bec0-c796bd251bbb.MOV

also on iPad running 15.2
