### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by MelloNholl** [ultrahorizon/UH-VPN-Docs#89]
good day. how can i add 1 more group to my account?

**Comment by jwsi** [comment]
If you would like to get a quote for your organisation, please email: [sales@ultra-horizon.com](mailto:sales@ultra-horizon.com)

**Comment by MelloNholl** [comment]
You service work?

вт, 9 апр. 2024 г., 15:26 James Webb ***@***.***>:
