### ISSUE TITLE
FEATURE: Add ability start UH VPN automatically on boot

### ISSUE THREAD

**Issue by marina8888** [ultrahorizon/UH-VPN-Docs#9]
**Is your feature request related to a problem? Please describe.**
No problems. 

**Describe the solution you'd like**
Hello! Just wondering if it would be possible to have UH VPN always on the top ribbon after MacOS startup? Currently, you have to open the application before the icon shows in the top ribbon. This is a bit time consuming and not so intuitive for new users/ non-tech people like me. 

**Describe alternatives you've considered**

**Additional context**
Apps like Dropbox and Malwarebytes as well as some other VPNs are set up to always be in top ribbon which, (at least for me) is more convenient. 

Thank you for your consideration.

**Comment by jwsi** [comment]
So we will be looking into adding a target into the UH VPN macOS app to allow it start on boot. This should solve your issues and @AnthonyWharton will revert when this update is live on the Mac App Store.

**Comment by marina8888** [comment]
Perfect, thank you!

**Comment by AnthonyWharton** [comment]
Snap, good timing! I was just about to hit send...

Thanks for that, I’m just in the tail end of finishing Windows for the release next week so realistically will be looking at doing this in the upcoming couple of weeks.

Thanks for the suggestion and support for UH VPN :)

**Comment by AnthonyWharton** [comment]
This feature has just been pushed to the Mac App Store, Windows to follow shortly :)

**Comment by marina8888** [comment]
Fantastic! Thank you very much. I look forward to seeing it.

**Comment by AnthonyWharton** [comment]
This is now fully enabled on the Windows release as well! Can finally put this issue to bed! 

Sorry for the delay, it got bundled in with a whole host of other features in a bigger release!
