### ISSUE TITLE
UH VPN not working anymore 

### ISSUE THREAD

**Issue by AndreaHerre** [ultrahorizon/UH-VPN-Docs#90]
Today my VPN stopped working. Last night it was working fine, so I don't understand what happen.  I try to open the program, and nothing happens. I uninstalled and install UH various times now, and it doesn't even open where to enter a new profile code.

**Comment by andrewlimaza** [comment]
Sounds like your key might be expired. Same issue, I couldn't re-activate my account :(

**Comment by andrewlimaza** [comment]
Also bumping this, there was a note about them focusing on their Enterprise clients only (Not sure if this means they've stopped all legacy users entirely on free plans).

See here: https://github.com/ultrahorizon/UH-VPN-Docs/issues/68

**Comment by jwsi** [comment]
UH VPN is no longer a publicly available service, and as such, legacy clients have been disabled. All previous users were emailed about this in advance and before service cutoff. If you would like to get a quote for your organisation, please email: [sales@ultra-horizon.com](mailto:sales@ultra-horizon.com)
