### ISSUE TITLE
Can't Make New Account

### ISSUE THREAD

**Issue by zach67385** [ultrahorizon/UH-VPN-Docs#92]
https://uh-vpn.com/auth/signup

Gives 502 bad gateway.

**Comment by skahtml** [comment]
Same

**Comment by jwsi** [comment]
UH VPN is no longer a publicly available service, and thus public signup is disabled. If you would like to get a quote for your organisation, please email: [sales@ultra-horizon.com](mailto:sales@ultra-horizon.com)
