### ISSUE TITLE
signup

### ISSUE THREAD

**Issue by ghost** [ultrahorizon/UH-VPN-Docs#94]
hello
and have a great day

im sorry how can i signup in hu vpn ???
there is no button or anything about signup

thanksss

**Comment by skahtml** [comment]
How to sign up??? i have error , you have something with your hosting

**Comment by AdrienGiboire** [comment]
My guess is this project is 💀

**Comment by jwsi** [comment]
Hi @AdrienGiboire , no this project isn't dead. It's simply no longer available for consumers to use as a standalone VPN platform. We now operate only on a B2B basis and if you would like to get a quote for UH VPN in your organisation please email:

sales@ultra-horizon.com

Thanks,
James

**Comment by AdrienGiboire** [comment]
OK, thanks for the information. I discovered UH VPN via Digital Ocean. I understand it's not a good fit for me.
